### ISSUE TITLE
no current Fiber, defer can't be used without Fiber!

### ISSUE THREAD

**Issue by tswaters** [alexeypetrushin/synchronize#23]
I'm trying to get this working but can't get past errors with fibre not being available... I've tried the following, the first one is pretty much verbatim from the first example:

```
    data = sync.await(MyService.find(key, sync.defer())); 
   // "no current Fiber, defer can't be used without Fiber!"
```

```
    var findSync = sync.syncFn(MyService.find);
    data = findSync(key); // calls async version, fails due to no callback
```

```
    sync(MyService, 'find');
    data = sync.fiber(function () {
      MyService.find(key, sync.defer());
      sync.await(); // returns values properly, no way to return
    });
```

Is there some kind of setup step I'm missing here?  The examples from the docs page don't appear to work.  Could this be an os-specific issue?  I'm running Windows 8.1 x64

**Comment by alexeypetrushin** [comment]
Thanks, you are right, some of the examples in the docs are bit misleading and need to be updated a little. 

The thing is, that you have synchronisity **only inside of the fiber**, if you would like to get results it should be like this.

```
sync(MyService, 'find');
sync.fiber(function () {
  MyService.find(key, sync.defer());
  sync.await(); // returns values properly, no way to return
}, function(err, data){
  
});
```

It is much easier to wrap everything inside of the fiber, take look at this example:

Demo http://example.monojs.org
Source https://github.com/sinizinairina/mono-example/blob/master/controllers/Posts.coffee

There's no explicit callbacks or fibers (but yes, they are actually there, created automatically).

**Comment by tswaters** [comment]
Thanks for the reply!  I was doing some crazy stuff trying to get async methods to return synchronously for use with a view engine that doesn't support async local functions -- turns out this totally isn't possible.  I ended up just doing the call and calling the render function with the results.
