### ISSUE TITLE
sync.parallel() should be a noop if sync.defer not called

### ISSUE THREAD

**Issue by bradvogel** [alexeypetrushin/synchronize#25]
My code uses a loop inside `sync.parallel()`:

```
    var responses = sync.await(sync.parallel(function() {
      myArray.forEach(function(item) {
        asyncFn(item, sync.defer());
      });
    }));
```

I noticed that when myArray is length 0 that sync.await never returns. This seems like a bug. Shouldn't sync.parallel know that sync.defer wasn't called inside of it and just be a noop?

**Comment by alexeypetrushin** [comment]
Thanks, yep, looks like a bug, it should know that there was no call.
