### ISSUE TITLE
[regression] Memory leak in 0.9.12

### ISSUE THREAD

**Issue by bradvogel** [alexeypetrushin/synchronize#31]
We're fairly certain that 0.9.12 introduced a massive memory leak. We create thousands of fibers a second using synchronize and have observed over the last week a massive increase in memory. I downgraded synchronize to 0.9.11 and the memory leak went away entirely. We tested this several times.

Can you take a look?

**Comment by bradvogel** [comment]
@d3m3vilurr

**Comment by d3m3vilurr** [comment]
ok. I created new pr. I think, it will help to be resolve issue. :)

**Comment by bradvogel** [comment]
Great, I'll give it a shot.

**Comment by bradvogel** [comment]
We tested this in production (with very high volume) today and it appears to work well. Thanks!
