### ISSUE TITLE
synchronize block main thread.

### ISSUE THREAD

**Issue by kang298** [alexeypetrushin/synchronize#53]
Hi all, it seem when using synchronize, it block the main thread,
for example:
- if you have a long time process, user can not access another page, right ?
this is the code I used
sync.fiber(function () {
importData(table);
		});
it seem the main thread has been blocked, anyone has the same issue ?

**Comment by bradvogel** [comment]
That is expected. Synchronize uses fibers, and fibers are only a way to schedule work. It does take advantage of parallel processing. See https://github.com/OptimalBits/bull/issues/392 for more.
