### ISSUE TITLE
Mobile compatibility

### ISSUE THREAD

**Issue by ketz** [alexeypetrushin/synchronize#55]
Hey guys,

I was trying to get this running on iOS, now that iOS 10 allows playing HTML5 videos inline through the "playsinline" parameter.

I can see the 3 videos displayed, I can press play and they do all play, but only for a frame, and then all 3 stop/pause, until I press "play" again to see the behaviour repeat itself.

Is there a way to allow for continuous play on iOS?

It's working fine in Chrome on a Mac, btw.
Here's a test link if you want to give it a go: http://bit.ly/html5sync

cheers

**Comment by bradvogel** [comment]
Wrong project :)

**Comment by ketz** [comment]
sorry! :x
