### ISSUE TITLE
Fibers: 'Missing binary. See message above.'

### ISSUE THREAD

**Issue by tenchugecko** [alexeypetrushin/synchronize#58]
Server Setup Information:

    Operating System: Debian 9
    Deployment Method: Git
    Node Version: 8.9.1 NPM 5.5.1.
    MongoDB Version: 3.2
    ROOT_URL environment variable (Is there a subfolder?): no, where should that go?

Problem description:

it works on windows after npm install

when i git it up to my Debian Server, it says

Try running this to fix the issue: /usr/bin/node /home/git/test/node_modules/synchronize/node_modules/fibers/build
Nov 29 19:18:20 worm _test[9284]: /home/git/test/node_modules/synchronize/node_modules/fibers/fibers.js:20
Nov 29 19:18:20 worm _test[9284]: throw new Error('Missing binary. See message above.');
Nov 29 19:18:20 worm _test[9284]: ^
Nov 29 19:18:20 worm _test[9284]: Error: Missing binary. See message above.

build doesnt work: node-gyp rebuild
gyp: binding.gyp not found (cwd: /home/git/test) while trying to load binding.gyp

i swearword had it working yesterday but dont know what i did to make it work.
I literally just had it working, and didnt want to post , now its here again.

**Comment by tenchugecko** [comment]
somehow the fibers in the synchronize subdirectory is now gone and itswrking somehow

**Comment by zakdav** [comment]
I think package.json's Fiber dependency needs to be upgraded  to new Fiber "2.0.0" instead "1.0.x",
Until that happens, if it can help you, I forked with synchronize_f2 which differs only on Fibers 2.0.0 dependency

**Comment by d3m3vilurr** [comment]
@mannyvergel updated package.json, but npm only can publish @alexeypetrushin 
btw, in my case, no more use this module except lagacy projects.
all new projects moved to async-await chain instead this option.

**Comment by mannyvergel** [comment]
@d3m3vilurr thank you, there are some legacy projects I'm working on. But thank you for introducing me to async-await, I'll start to use it for succeeding projects.
