### ISSUE TITLE
wrong version of fibers on package.json

### ISSUE THREAD

**Issue by outreal** [alexeypetrushin/synchronize#67]
Hi,
The fibers dependency on package.json on the latest version of this github repository (https://github.com/alexeypetrushin/synchronize/blob/master/package.json) is "^3.0.0".

But when I install synchronize with `yarn add synchronize` or `npm install synchronize` on node v10, the installation fails. Having checked the `package.json` on my newly created node_modules/synchronize, that's what we can see:
```
  "dependencies": {
    "fibers": "1.0.x"
  },
```

So, I don't know how, but the published version of synchronize doesn't match the version on github, which looks to be fine.

Could you please publish again?

Thanks a lot!

**Comment by zakdav** [comment]
Use a fork like 
https://www.npmjs.com/package/synchronize_f2

**Comment by outreal** [comment]
Thanks a lot @zakdav
